name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 91.228.153.121 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh root@91.228.153.121 << 'EOF'
            cd /home/cleancar/web/reservation.cleancar.az/public_html

            echo "👉 Pulling latest code..."
            git pull origin main

            echo "👉 Installing backend dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "👉 Running Laravel migrations..."
            php artisan migrate --force

            echo "👉 Caching configs..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "👉 Installing frontend & building Vite assets..."
            npm install --legacy-peer-deps
            npm run build

            echo "✅ Deployment finished!"
          EOF
